# Generated by Django 5.2.8 on 2026-02-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_education_employment_project_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='avatar',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='vibe',
            field=models.CharField(blank=True, default='Feeling adventurous', max_length=200),
        ),
    ]
