# Generated by Django 5.0.1 on 2026-02-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_boardcolumn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Backlog', 'Backlog'), ('Planning', 'Planning'), ('Upcoming', 'Upcoming'), ('Completed', 'Completed')], default='Backlog', max_length=20),
        ),
    ]
