# Generated by Django 5.0.1 on 2026-02-06 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_connections', to='api.couple')),
            ],
            options={
                'verbose_name': 'Daily Connection',
                'verbose_name_plural': 'Daily Connections',
                'ordering': ['-date'],
                'unique_together': {('couple', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyConnectionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.dailyconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Connection Answer',
                'verbose_name_plural': 'Daily Connection Answers',
                'ordering': ['-answered_at'],
                'unique_together': {('connection', 'user')},
            },
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('connection_answer', 'Connection Answer'), ('milestone_update', 'Milestone Update'), ('task_shared', 'Task Shared'), ('message', 'Message')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('content', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to='api.dailyconnectionanswer')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_inbox_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BoardColumn',
        ),
        migrations.AddIndex(
            model_name='inboxitem',
            index=models.Index(fields=['recipient', '-created_at'], name='api_inboxit_recipie_62df26_idx'),
        ),
        migrations.AddIndex(
            model_name='inboxitem',
            index=models.Index(fields=['recipient', 'is_read'], name='api_inboxit_recipie_a9a637_idx'),
        ),
    ]
