# Generated by Django 5.0.1 on 2026-02-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyConnectionPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField(unique=True)),
                ('category', models.CharField(choices=[('deep', 'Deep Conversation'), ('fun', 'Fun & Playful'), ('gratitude', 'Gratitude'), ('dreams', 'Dreams & Goals'), ('reflection', 'Self-Reflection'), ('appreciationation', 'Appreciation')], default='deep', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Connection Prompt',
                'verbose_name_plural': 'Daily Connection Prompts',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
