# Generated by Django 6.0.2 on 2026-02-16 01:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_user_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='userprofile',
            name='unique_normalized_email',
            constraint=models.UniqueConstraint(fields=('email_normalized',), name='unique_normalized_email'),
        ),
    ]
