# Generated by Django 5.1.4 on 2025-12-23 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.couple'),
        ),
        migrations.AddField(
            model_name='activityhistory',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='activityhistory',
            name='completed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityreminder',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='users.couple'),
        ),
        migrations.AddField(
            model_name='section',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='users.couple'),
        ),
        migrations.AddField(
            model_name='section',
            name='parent_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='activities.section'),
        ),
        migrations.AddField(
            model_name='activity',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='activities.section'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['couple', 'display_order'], name='sections_couple__84c875_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['couple', 'is_deleted', 'status'], name='activities_couple__9f644d_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['couple', 'display_order'], name='activities_couple__24cfdc_idx'),
        ),
    ]
